apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring-todolist-app
  namespace: argocd

spec:

  project: default

  sources:
    - repoURL: https://github.com/HoussemDhahri/MERN-app-End-to-End-Project.git
      targetRevision: main
      path: Kubernetes-Manifests-file/monitoring

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true