apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: todolist-frontend-alerts
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
    - name: todolist.frontend
      rules:

        - alert: TodoListFrontendDown
          expr: |
            (
              label_replace(
                kube_deployment_status_replicas_available{
                  namespace=~"todolist-(staging|prod)",
                  deployment="todolist-frontend-deployment"
                },
                "target_namespace",
                "$1",
                "namespace",
                "(todolist-(staging|prod))"
              ) == 0
            )
            and on (target_namespace)
            (
              label_replace(
                kube_namespace_status_phase{
                  namespace=~"todolist-(staging|prod)",
                  phase="Active"
                },
                "target_namespace",
                "$1",
                "namespace",
                "(todolist-(staging|prod))"
              ) == 1
            )
          for: 2m
          labels:
            severity: critical
            component: frontend
          annotations:
            summary: "TodoList frontend is down in {{ $labels.target_namespace }}"
            description: "TodoList frontend deployment in {{ $labels.target_namespace }} has no available replicas for more than 2 minutes."

        - alert: TodoListFrontendPodRestarting
          expr: |
            label_replace(
              sum by (namespace, pod) (
                increase(
                  kube_pod_container_status_restarts_total{
                    namespace=~"todolist-(staging|prod)",
                    pod=~"todolist-frontend-deployment-.*",
                    container="todolist-frontend"
                  }[10m]
                )
              ),
              "target_namespace",
              "$1",
              "namespace",
              "(todolist-(staging|prod))"
            ) > 3
          for: 3m
          labels:
            severity: warning
            component: frontend
          annotations:
            summary: "TodoList frontend pod is restarting in {{ $labels.target_namespace }}"
            description: "TodoList frontend pod {{ $labels.pod }} in {{ $labels.target_namespace }} has restarted more than 3 times in the last 10 minutes."