apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todolist-backend-sm
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - todolist-staging
      - todolist-prod
  selector:
    matchLabels:
      app: todolist
      component: backend
  endpoints:
    - port: "3500"
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s