apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-backend
  labels:
    app: todolist
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
      component: backend
  template:
    metadata:
      labels:
        app: todolist
        component: backend
    spec:
      containers:
        - name: backend
          image: houssemdhahri93/todolist-backend
          imagePullPolicy: Always

          ports:
            - containerPort: 3500
          env:
            - name: PORT
              value: "3500"

            - name: MONGO_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_CONN_STR

          startupProbe:
            httpGet:
              path: /started
              port: 3500
            periodSeconds: 5
            failureThreshold: 15

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3500
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 3500
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"