apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todolist-prod
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: houssemdhahri
  MONGO_CONN_STR: "mongodb://admin:houssemdhahri@todolist-database-service:27017/todolistdb?authSource=admin"