apiVersion: v1
kind: Service
metadata:
  name: todolist-database
  labels:
    app: todolist
    component: database
spec:
  selector:
    app: todolist
    component: database
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP