apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todolist-database-statefulset
  labels:
    app: todolist
    component: database

spec:
  serviceName: todolist-database
  replicas: 1

  selector:
    matchLabels:
      app: todolist
      component: database

  template:
    metadata:
      labels:
        app: todolist
        component: database

    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          
          ports:
            - containerPort: 27017

          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_INITDB_DATABASE

            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db

        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.40
          args:
            - "--mongodb.uri=mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@127.0.0.1:27017/admin"
            - "--collect-all"
            
          ports:
            - containerPort: 9216

              name: metrics

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc