apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: todolist-prod

spec:
  encryptedData:
    MONGO_CONN_STR: AgBZl97Q9Mn9jAmiDUrQySvwtij5xvbnqIqte0jhipwFo3X4Gc49pd+M0n91rnZYFey7nA82O+llu46sSRrazTU8LTyNTgOmePvJS2ejyMU1VvZJvcwTD+npYCxntE/a+iLaFeGcrYBeq0HJN/qA/WxeHNrpvusngElJeBhldbuGhybcCFxI2ReSDNxYtm+6Hb9btim44ybC7FvoeIpgN+9TaYKImuewiUOLcIdVIIQYDxWpmhjC9kurq7SBmkTzZN5TnuJiE8k4HXVDH0By8Nq0YbpSMnOxP+65kVcGKPKMt1jrCW4vZTLrQjGvpoEq8VAf4rI3VGJ7SjjjrXCF4uv9U4/JqZvT9lMekOkF42sZwe7AT63cSP8k4EgYkY592jHNeLIOeno0V+aXU41yQfacB3+q8RI+Fr7KTOJOkg1QFCELRxbXz8pBwmKMQTq6mUgPRQoQEPJnaVAT0u5a88Qm1PlYhGCWLgQizmhbmyKBIl3GAGG8XD/nl6eP2RJAd+mRcu9z5PoOzyDHJyfPcmG6I30eawRhn+Odj37WpFBXO2BqKJ3I1CKegVif5C25+59MOmUk3CtTq2WhVl9T8/ewsvaol7XbMSshyaW900zJZS1LXUXEwDTQqLgr6qWyagWGRN1JXnkjK7orjZqnKovOfq2P9qlK5fCNI7CA1m45Iiu8BwyxTJEAtW547xbS3IZItY7ZMkOeXm1BFHFJn0f3o68ot2xFiugqGQ//OS6L49wb2mlR6z9j9d6M71YYliNeapNL+wK9Xz7er8Ogy9OpcYwvjdKw3BJW9qAfR78U30Fs3LmWCsXbSQ==
    
    # mongodb://admin:houssemdhahri@todolist-database-service:27017/todolistdb?authSource=admin
    
    MONGO_INITDB_ROOT_PASSWORD: AgBskAjOFYF6NvdohggAH+/OtRD8U8Ff4a8e7sSden/Grlc4SgxKMRtRrq8Wq9X2CZ1IU4vQGWrh1rYAy+Y5UvLMwFrYKmN3ynBJM4ppIDyaL6hoSlosGSaGRRE3iP1b4ujrAGwxrB0hcaJmLYGvQP0aFDp2HnKpuve/lz9QYYQ2+dUNyD2kDt02+eIk5APhBNcQf3+OF9Gu74DCDiWRMIHt5GnPfhDbQHN/ZzuPrYxmXTrIS7TZqcQWLPplNgGQ0072mGWR7EmlwRs6sEJkwrOU8ZJ3P0S0uMrmMPB6hSGncDbapaGQJ2siiq/3S98c4J8jJJKiucoVV1UrZcSBBiWPuKJbaCoYKa3Ku3X0lHDLZ05VPwmcX8lvMSAvIHFxRoUBmOLl7kelFe/knppOsoJowD0oOSHz4wgBo19svVVRvf/AuR3C5s1eS1oHaqWfAE5NxYfKxXLaFpn6iiXA+sMUtwnOWz2DKthFnkj0TBzk9fLuktaLa1Q1K2tp378YfN7/gd4hyjU+7LgkK9K+lbL/rfm0Rt2ACSQo1Jo3v4wtVYUXvtoxGlHODm30CC8VBjHQGU7PnUjpa5vItTEouXC0gUD0Fs+0EUy0o83VBHdvzUiFvdggs/Nn8etJJCYOUqXIlIgi1hMvFNkgOnyVkxhGOtHlDDExQmsQ1ShISa8qcM/q7uzReUuqS86GlHfHdMYLsF69pUUAQtj11DxK
    
    # houssemdhahri

    MONGO_INITDB_ROOT_USERNAME: AgCZP7L7feRnYkP/bUEgpNqAHB8Df8tMMaQZ5nE2ZyWI3P8VR/CHhtKVtuCdzx68EVI3ScQwd0i1Bz/2btbYqiURikWxuaQM67eoKJTyXjrFnL/w6VBsStJK50Xw39qH4WSr42NrbCPw+QHuLVPN09HCJ2jKoyetARhy4EiJj/VHQfjNq2/SfTpVlThAe7Nt49iDu51SyTfe/XmIrKgsiHqz2ztoiCVT0sVSv20CGHeYeUVG4v12nIWs9qcGy2ABDEtHoCkfKi6uxhXzSF1Gepi8fDE+cplR28/DrKICqvvOawjJGHP+T4secd5LVxaZMCR2dhHs4USKRmxagIZPFFWOtlJm/+Hucwf43atNFS35WJMVot0uBTslUV3sJVB+/wbrCKjCW9SyLb27GA4cdK1lLIL37b81udjJ6qfLbzfk2IRtWypKWDIKpdLS2d4iER4TgqWYNkf/2wQNiT6N4A8IzyxQfznWUMZEt3nN+RJD1WAU+kzw5cqIN8bebfYlaGqwlR0ERRQUMElKNPpfBuK6ER294W5ukes3HvfEx/6UcpYfw3EvJ9iJhz5a4HjZKPGMl49o1G/zmBqjjmh64zxk3REuukpNqkeBT/nMwWSqza0Ok16IK9MfoCPtF4//jwd0sAvWRgTNxDLl5hSkuva+hXd/NDVJzY1Djjr2RTE3GVJlBLjf0gplfn/WSdlC26s0ncj0Nw==
  
    # admin

  
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: todolist-prod
    type: Opaque