apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: todolist-telegram-alerts
  namespace: monitoring
  labels:
    release: monitoring

spec:
  route:
    receiver: todolist-telegram
    matchers:
      - name: component
        matchType: "=~"
        value: "frontend|backend|database"
    groupBy:
      - alertname
      - component
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h

  receivers:
    - name: todolist-telegram
      telegramConfigs:
        - botToken:
            name: alertmanager-telegram-token
            key: bot_token
          chatID: -1003954919587
          sendResolved: true
          parseMode: Markdown
          message: |
            {{ if eq .Status "firing" }}
            🚨 *TodoList Alert*
            {{ else }}
            ✅ *TodoList Alert Resolved*
            {{ end }}

            *Alert:* {{ .CommonLabels.alertname }}
            *Component:* {{ .CommonLabels.component }}
            *Namespace:* {{ .CommonLabels.namespace }}
            *Severity:* {{ .CommonLabels.severity }}

            *Description:*
            {{ .CommonAnnotations.description }}

            *Status:* {{ .Status | toUpper }}