apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-telegram-token
  namespace: monitoring
spec:
  encryptedData:
    bot_token: AgAUUVZ2sTT4+Cnf6xhX/y7PNJ6ZG/czsvLzB3QZlqAYr0UCuSlLe21nrgm2WBcKRUh5Q6Oqw5aZ5ca1LMKmdbO2k882CqtRzs2r3H5GFsB1E0l/bXPJUo5Gx8yubPhRUbpbr64KeAfBG6oQES1e4XkIf7YDTowiJtEjbK/MfqXt2VnTnM8sy1yp6GYsNUhDW26s3p1EvyKT4lKEyg6P/eb4aP/Ui6xM0Y5iVzGD4lPxVtdJ6zkzD5aY8lFbdZbX544V4yvrdDwjiQms+MSm5Tb1f9eVN/spRXIMX8ae8bmHBRUwoK0qHQy4aMvWk5JDsM8azq4ryaNE7j3R5j6hHysRkcHCP6ruSxh8jPMnKcumogabp1gxAXcFmIclA4QyyP8GTJJkVU/gTqHE2HJ8+rvyBPcUJIYg4Xg1RSRXxCOykyRbw/6em38q3Sa3pDfFuave7q1EMzLVH9gNPV5Re4f5BgjbJ7RRl/It+hCJbGAVhhuLIepBsqZoF1KoYn7ZbystPC29VkrvBEm/suoqijKoQ7IXjA9NTBDXWkAjGufe5qoIreDSc54f1Y7lZ+TnMVPty00FgDZd1yBmsCocVfLTtCZvOzw1qPgpOBm81F6CEfdMJTjzLvEbmxIdfKwM/EUd/619ARL3kEu2TsZb6bQ4RmB4N54PQcX3F99yCs7OzlpxCF5P7hsW8uyVKr/11zINuFWwpnRXkQhZeLluM7AdEYzI+L2hgbOZa/fAwx8gucwH2OfKf5Wnxo7n8O9d
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-telegram-token
      namespace: monitoring
    type: Opaque