apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-telegram-token
  namespace: monitoring

spec:
  encryptedData:
    bot_token: AgB1EdzUyVnFSjqFJD4RZBWtBQsZbtThjAC/QWyIB11O6qsJfJ/1MbvYHlaVTOHOZwvzXG9BHFK/MzSMWSZiLy1ui9zp3AEgTqW3sNG+1/nskly63UzEy9wVNsv+qMev+eYl48S7u0jvKLSI8YHQ5S+s2NzWnr+QLzSlpjTmp0e3ZYZKLT2NJoprKg8EbVnZnyBexA/bF1jsoofWP8zR9E1b3J6znSOGO27ChaVUllitUf4amDBPUpY8vlRhLtxlPNY+h1PiAiJQ1otv9QZJfXHE6tMbJYEr4uU6V+z5bOh769tDrfgSZbQVDagGPK0BXS3k76j5wC77p+jrOMXpvMLQ7M/5Ri8+Q4Yt8WSbwwMeKqiesjkuDzjmybCuK5P9X7zaBlkRkAKinxwelqPuLyKBkF/vefMM+WlXzuj+fmwPKGeeSJb87ukIiJYesrhRCitbwjjTIAM9dJFjEHXfyE09lEF5+5pSnQScxE0LxVosW5bCMVajm5iZu6tbNg/WN8D/WHh1bgyRpHKtXRPqvL0IsIpyZgiN/Jp3JxSEIP+m/mXqJX94clExfSDK/1IWmP8okRkBMhk6Rh9EJp5lMeo2auqvxMPFtSaanEV+AAYkW7gFzv+0SF5bhbY9tqJ/lwM2xrLuDlFDgpPlReWd3PTIqO+AcDHUw8Z5/cVbttDm5ncbyaQsA5gB0F+wKpCQhitzs0KEw3ooqj4qg9cLw8CiM0WHq2afAsqb/EOMt8rb4DdOd7aluHQWRUk9Enxh
  
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-telegram-token
      namespace: monitoring
    type: Opaque