apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todolist-backend
spec:
  namespaceSelector:
    matchNames:
      - todolist-staging
      - todolist-prod
  selector:
    matchLabels:
      app: todolist
      component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s