apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todolist-database
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - todolist-staging
      - todolist-prod

  selector:
    matchLabels:
      app: todolist
      component: database

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s