apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: todolist-staging

spec:
  encryptedData:
    MONGO_CONN_STR: AgCXmsftWMNJmU+ExUEv/bxVQJIwVsdUOqDV5t7yh8pums6MxIiiWGCYoBerLFADQljsRMcXluxmsWpOJHItp8JBTeaxoo22vPuWPpNO2VDjfeA2E4JimjvuFg5fu5dIvadCXhSBuha1e18GGqSY9hRtAOy0vsFQ9snLbyhH5M6HAbHJOjSi6WPgbLOtKM7wX3gAjoHVOh1hKkxPu0Ev3zD/d4IHzcC1HeKOFd1dR51qFgaA9us4PwWxuNMP1VX4MihPeOcCFkH6lOaj35DHIMpGEMrnLWhXrrG1vPvd92Vc8D4DIwOa9y0NodeuozChcsHnB9LzDlTOUUWvjZo1uYHt84nrUfMIIi3GLWasm3+fDwPuFF1WGjQwZiDPM9nOZhn615KwWSfILH13Y+R4OcXnUNHYTrlxESSx49OtJ+E+psfXYL3rH68IlkW8HiclOTj7O9LI6OMRS0Y/byBMHhBStuJRp3moM2qvqk28O4lhrhw4H2w0dYPg4Pgv5WMoHaTfV3a2ybBvtn0InOVlt7AGbXosjn5IzWhVXLi2dqlSsvbpAHNNuNDxsmK5K2nbdl4q1sdVGDo6WCvlB5fOp3mPQNq+sMvl3AW9ffljflOwATbJ+/ANkZARqDhXHv6l1E2nW+v4bKQKlrAfkiJwtLNBoeBhKZF7jcWLeLUAxdT+v4oP6ICSA+/v5K6hz3U5f98kx7AVXkbfRkHTYGIPMoRksAAqx08jXazV3Tirz0s5suWW4qlIsQlHZT1VBOAgLV2pXJaHZ59gYqHbxq+oRgnsCzE6G/nP4KrjzTKMPZqEraj1
    
    # mongodb://test:test123@todolist-database-service:27017/todolistdb?authSource=admin
    
    MONGO_INITDB_ROOT_PASSWORD: AgAWmZdRo5KIQTnuJPc4IfHIj4QCd07CgvVJ02K5rUHEGfU/26Te/M1CAJSXrZBxiQyY7U6+gPrM9G+RXzJvjUBAk64vz7LQ+U2tWuQCi3EhdvfTCUHe7JaWtApPx5KRWCwqJpmlCVkBix16rCBm0L5s4gI0oVtVKpauxV/mS3A3HJck7tMVN+3ePFOV65cZywPSR30bJxgwz8t2JPUq132Vva2xjfT8zTSa5gOiafRokMfbkc5blVj8bAmD4llBCq8ijxjQY4ZcLHYdd6HlNtlIN/zhBeX4wxZlJY1MzFqQC//2+9OGviq7G1a8wfhtXLm5jtuYoN6CwvRjpFFTA17BtMwdT90whQISMNNLOq/fYwUPDhUP6cJyHKZrE3QcVwc8+fk1N1ppv7T85+0RNwBsqiPE04xrqBFMpmGwkHA9ZS61MPGogBnwGF5qr7WOZHIS0ARW6MLorJtU5ey9vUrEUKxMcC8pNusXNmEdo2B8LO6nom0iSsSQzAOn4Kr7YleYHznU2gc+v/E5OB1wZaEBI2IbWM+DskJz+utnRLBOmbtjQ927+0MIhqwhJ+YCA0wvrp/USDZ4m83XWxTNlmsCbfSWiNOagF9SmdpXFkxt5dCv2ujrIdWXI/oPKy5CiRpR0+TJk8Vze4B1uNEw+iIIK/An+y/L/rbK8zF3mk5SD9sUSkc/PzRGVSTwOORH+fr2XaniD3Om
    
    # test123
    
    MONGO_INITDB_ROOT_USERNAME: AgAunFEGbu/e43zm54iz+6O+epllMaejnXfhxgnzOmW+M2/757Ta5InXUcQhoRD2TPny43aTef8jKrXRaThah9cQyoMJfPTXNaqJrbmFEe7DSScHYLn9Byxqy1HlyxplQop1j7SpebR0Dy8T46tKjg2zk4ZEKxe6nuBAlX6k4Bpr1xT4AjFWUFXqtUvZmMPOQJLGSy4E8/K8WQlP5AO9/aZhy9Y8/XVlsKlHGQiFeP6N+XENCAGYt2XavjAteZt96M84H1ALYknLivR0OUqQ8QH0ukVDDp7rytWNPXsu33umazNE6S6qZmvGS/lXiZ6cbHr3BrBThVF6W8CNIFTcxrBFdtlBE7dCs3lffxvnHZrf/IQ2EIeabXRqVme8NQZBgHJ0Pfg4Qfi0Sv0nZf49Ayzlhxifh20dX9ZetlPRX1DLIfQKQdnnQT23PTnBCDPsmpadtOsQOreDKQSk/NR43+nH0yKFEuouPSIQ332I4TJR7Me+0OSTt/th8kyi1VIH6C1zn0CSy3QaYOKcH9g7k6a7+Hd38VDojH3jkkQz0c6F15tSdF7d64cEYPNhrwE1YoHodENHxzMgC+HKHrStp0WC3IucruWlK0Y6wzJFapfJAhQ48fkwDsYyvyK/WXk3pbnXyUl8yiBbw7j0vCIeGP1RhbW/DE0Fn63QqZC71klfpCpEfBxysgolpDa/f0+53nZJWFKo
  
    # test  
  
  
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: todolist-staging
    type: Opaque