apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-express-secret
  namespace: todolist-staging

spec:
  encryptedData:
    ME_BASICAUTH_PASSWORD: AgCGJ35NiPhWS6hJo/2stOU0VTgq7dMLuNIKXhjk7nINEJ43I+Z0dsxDEsjj05gcGBxZTs+igrFLzceXF9sdSUxQak6CzepodjAAADphnykOUCr0eWi/OUNorb9t0Jksg0dCPei4icoGEdPEjHvIGt7Z/uU3tMTQ8RfeJmbQEM0Jd72a5LmqWPF+oUz+wC7gsxfniZ+Kr1SwWRDFiAEYNGZTstfdpEks9TZR+MJTCRKflxvjJkGQYLI4N6rLScHTFKmcROsgCfpBQe6A1MUBqxpUNPtPbXKtUb/unYGVEFwzNCxG83O/91Ll/OMFrwp3GafL9a4g4KJMTn0cZQRfFpL1fIi1cjSb9vXDRpv2P5STBvD1+ylSN/bqRO9uJTNH7SXvpZQBjz8+3PkFRSePKm/6SKVzKtROrHC/OnSO2rVvrQibpsSEk8f36QBpe04ECrvL8s/FtM6S0o1HxH0kTH0MEuaS2XCwt4m7kZy7qJB197Q2GcIv5qE/CW0j6Hdclw9HF5XGDLQzhUjB5gDL9zvhsJqJWBeGONP4CjQqX+4wXE30zB/bbKwFrkVgFSXrIEWr11Dj8Txzahji9k9SxfSk8dW6JaSao0OOJk6fGD5VLIqIWFdi63ejUeQJh0Tl4QhipxsAxU6M4GJltpYw7dq2UN3p+8J9vZgXZNtVEOoOVAXGocWjGfT973IeniTySapijayBsw==
    
    # admin
    
    ME_BASICAUTH_USERNAME: AgACX0hyaxbzNM31w88AqYJUgEK21Az7ItsF6rLv6Itz1zZRPLS7iyK4b8DwCkwe3posafqZChENswsxA4sB1gVqi/himiqFDNskJb3+QgN5qaQ//ZPyc+TC7lzWAKk+V7zQQZJKROSkUiU7UvwUd+NSidqcN6329KlGdWvpYi5asJw5cfqf6zJNnItLDpVmOgKBDrKF9xadPIWAG72cGxzT/sEDWJNxajrLl/IuOyzI4gBYZYaAgzF93nQWu1pJQ2DDR78j0//XhU4nPUD1XWMbOm0gk5jpjpo21XG+qZp/WKt5jRZRGFzdZDAKdUCdMopq4QK6GUOphqZZA3RYhfyHOrDxdoEp3VZTdxdXbBuwHYqisa6dg38Xjeew8Zn+K1tkLh1Z1TWgdpOkgWV11gsydIGJoruYly9YUFcezjlgM98EDmmmgPxXhSGjKISrRUVwF5N+ZhLCAnZbYFVqvPSRXT9TC850fCHZ0GhXN71ViobHwPazBYzC8vPSyNeB0oMZ13ObLe4Ksb9aiB3yg0zDSscnc27D4fzbjqih8vQByfyA8Pq3VcBbv7Gj5zC3gUlw+PANQLJkoQqMQXY9z19iL5M8KLVhv8oXL/hm/bHl2wwlgViCNcsC428kKJZRTJPrO1mUAxkZl3FVtdDjEplKocOJ/RSCpo7cvSj0DlDdOkywMGg1exLj6SKz07Vlgwe8LQ7sVw==
  
    # admin
  
  
  template:
    metadata:
      creationTimestamp: null
      name: mongo-express-secret
      namespace: todolist-staging
    type: Opaque