apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-express-secret
  namespace: todolist-staging
spec:
  encryptedData:
    ME_BASICAUTH_PASSWORD: AgCJgfYqxn5jv55A4JKVEDJEsTs/QoxnvB3bi//isiH4ji8squq7DkmDtocYagdMFFOIPXmpwv2WS7g/b2IFwheL/EfdEd7tbfp2ERYSdx5bf9d4LDhIDxlHFAdxz0kxdBMyQHMpA/XmrjZDWjcPK0ZBhBVO9pe2QOUoAabvZnKOWRljIKbU4pRB9emxmQk2DJ2hOn95KZ7pq93MAKjP7+tDDl1ChSHg7xLNb90JMaAqBvwxGX0TNIZnOFNL7AoItBr1m2MtH1xPWBzsWNK7J8A0030TXSBOH0bc/r3LTC1Z0PPT8G/GwhqQH3VQbf/DEmwRS7jUK7bp7kqEc/bKZyaLTrX6wYcvJt9jHjwBip+pR3Kw3ShKnp6iTuHM466OYdqI4MgNjyKsiLFKZd8aANzesBji6M82A9cZnwpvVonmKUxtCWQjSaacXLjPUZo5QvHIgDVAxA8+QpWQkUGgIWYU7vEcS5M+Kwaopo+y5B1BI9StQ1FeIlplKThE3ZqALgvzhq59wUgNsQZATVxlTCgp4EqBV28BhqjMHaeh1rHIzGalRiTjcG0RPi0wTkrVaTAiGmmfLzI8esHchMPCifu5Ys6SN56pD8d1CJ5mMgTZKBrwhJ/cBUarryiOUTl+tA+LOplU6NOZf4hFg1+YmYUHcXraWb0xyQKiNR7M47U8DQxk3hnumBl9K3RfEvh/aPd0zMGW7g==
    # admin
    
    ME_BASICAUTH_USERNAME: AgA/eZ10g1rUZEyBlUwAdHy4eXUw11JSfYT/oT/6pNc4GLEwLz/apR66pLr6bQ5nTK4ZFYvjkVc9+3T7pR3Ky9E7X/O7rBAsYHgbIY3RkagsG18+7cBL0x4iccQwiLLW40debjxMjgyqsJrxCwrRrTXSofLzP1HgLl4hwJnRqmUIaSrxI0nqkmpjgHdTCHPqT+682JN2BWoTd+esxYei4X658OIzZGPJBGIiTuaWoAI+lGU1jzxxEvMx9ksWPPIK0zkNHLWqx99pYbQlh3/y5A7BrdcPZSsCH+UKIQOxw58faW1mJH6HXAHDB8olQQ2YyYWNUeqjbX2sCzDMCGcqFPEcJSebFzyHgLUBRIpBJ0O3hPsJHDhAzO58MKhAdvZKAGGVrTBjt5deELAAeuFUXacIUerIjbx9ldrZXe5yuzjnBk/3xDdMrhPMVtHojSvgOZvaGZDoGCvFcu8prqQ+h+eiN/n/jgPCEfjpztylydQBxn3sFh6Njk0ZX8d66SKDTUXR5LEkQmITb/oYsj31OU6I5X3MyJBlmyb6gbHQRF2ynO2rJbqJVbX6Fe/BNwBs/i9Lqb1epzKKR19MAPTZFNEtm0I9EBxywh+Z7OOmTCTvwfpNP1HT94JtUgvo00F8k7SIs6gQVwP+m9RSkB4GDUiUHk7Ya5YyIA0NoZa9GozLB/6c0eHBSwrosz+QdPB5t3+kOPc+LA==
    # admin
  
  template:
    metadata:
      creationTimestamp: null
      name: mongo-express-secret
      namespace: todolist-staging
    type: Opaque
